#ÅäÖÃeureka×¢²áÖĞĞÄ
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
  instance:
    hostname: localhost
server:
  port: 8080
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/lover-MXL/spring-boot.git
#          search-paths: /spring-boot
#        label:  master